# Generated by Django 4.2.7 on 2024-01-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Albums', '0002_alter_album_musician'),
        ('Musicians', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musicians',
        ),
    ]
